name: Response Time CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types:
      - response_time
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@v1
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
